baseURL = "https://v2.56k.cloud/blog-v2/"
languageCode = "en-us"
title = "56k Cloud Blog"
theme = "ink"
paginate = 5

copyright = "Copyright (c) 2020, 56K.Cloud GmbH"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#googleAnalytics = "UA-123-45"

[params]
    subtitle = "56k Cloud Blog"

    # Optional 64x64 avatar image
    avatar = "https://56k.cloud/img/56KCloud_logo.png"

    mode = "auto" # "dark" or "auto"
    # customCSS = "css/custom.css"  # Custom CSS applied to default styles.
    # customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
    # customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Navigation
[[menu.main]]
name = "All posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Home"
url = "https://v2.56k.cloud"
weight = 2

[[menu.main]]
name = "Training"
url = "https://v2.56k.cloud/training.html"
weight = 3

[[menu.main]]
name = "About"
url = "https://v2.56k.cloud/about.html"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/56kcloud"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/56kCloud"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/company/56kcloud"

[taxonomies]
   tag = "tags"
